export default function Home() {
  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: 40 }}>
      <h1>Digital Life Backup — Starter</h1>
      <p>This is a minimal Next.js starter app generated by ChatGPT.</p>
      <p>Connect Supabase and Hugging Face to enable AI features.</p>
    </main>
  )
}
